# These are supported funding model platforms

Bitcoin Address - 1CxC3hsrw1yFhj1fQfazaeCaqwVeeMfxBz
Ethereum Address - 0xf5A4526D22FDDE2F96Dcc6de54f43012D958dB7A
Dogecoin Address - DLMonAvDVC8oUvE3UaUYV5hzicnvcRK7jS
